/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package forms;

import classes.BD;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Mypc
 */
public class Consulter_Etudiant extends javax.swing.JInternalFrame {
   int prc_livre ,prc_revue,prc_art_recherche;
       DefaultTableModel dfm =new DefaultTableModel();
    /** Creates new form Consulter_Etudiant */
    public Consulter_Etudiant() {
        initComponents();
        jPanel_etudiant.setVisible(false);
        //Ajouter les noms des colonnes
        jTableHistorique.setModel(dfm);
        dfm.addColumn("Nom");
        dfm.addColumn("Prénom");
        dfm.addColumn("Nom Materiel");
        dfm.addColumn("Type Materiel");
        dfm.addColumn("Date emprunt");
        dfm.addColumn("Date retour");
        dfm.addColumn("durée");
        dfm.addColumn("retour");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        recherche_btn = new javax.swing.JButton();
        cin_txt = new javax.swing.JTextField();
        jPanel_etudiant = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistorique = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_1 = new javax.swing.JPanel();
        jPanel_1_header = new javax.swing.JPanel();
        jLabel_livres = new javax.swing.JLabel();
        livre_stat = new javax.swing.JLabel();
        jPanel_2 = new javax.swing.JPanel();
        jPanel_1_header1 = new javax.swing.JPanel();
        jLabel_livres1 = new javax.swing.JLabel();
        art_rech_stat = new javax.swing.JLabel();
        jPanel_3 = new javax.swing.JPanel();
        jPanel_1_header2 = new javax.swing.JPanel();
        jLabel_livres2 = new javax.swing.JLabel();
        revue_stat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Consulter un étudiant");

        jPanel3.setBackground(new java.awt.Color(223, 230, 233));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Entrez CNE de l'étudiant :");

        recherche_btn.setText("Chercher");
        recherche_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_btnActionPerformed(evt);
            }
        });

        cin_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(cin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(recherche_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recherche_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cin_txt))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Historique des emprunts:");

        jTableHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom d'étudiant", "Nom de matériel", "Type de Matériel", "Date d'emprunt", "Date de retour", "Durée d'emprunt", "Status de retour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableHistorique);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Statistiques:");

        jPanel_1.setBackground(new java.awt.Color(255, 177, 66));

        jPanel_1_header.setBackground(new java.awt.Color(255, 177, 66));

        jLabel_livres.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_livres.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_livres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_livres.setText("Livres");

        javax.swing.GroupLayout jPanel_1_headerLayout = new javax.swing.GroupLayout(jPanel_1_header);
        jPanel_1_header.setLayout(jPanel_1_headerLayout);
        jPanel_1_headerLayout.setHorizontalGroup(
            jPanel_1_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_livres)
                .addGap(78, 78, 78))
        );
        jPanel_1_headerLayout.setVerticalGroup(
            jPanel_1_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_1_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_livres)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        livre_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        livre_stat.setForeground(new java.awt.Color(255, 255, 255));
        livre_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        livre_stat.setText("jLabel4");

        javax.swing.GroupLayout jPanel_1Layout = new javax.swing.GroupLayout(jPanel_1);
        jPanel_1.setLayout(jPanel_1Layout);
        jPanel_1Layout.setHorizontalGroup(
            jPanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_1_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livre_stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_1Layout.setVerticalGroup(
            jPanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_1Layout.createSequentialGroup()
                .addComponent(jPanel_1_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(livre_stat)
                .addGap(16, 16, 16))
        );

        jPanel_2.setBackground(new java.awt.Color(184, 233, 148));
        jPanel_2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel_1_header1.setBackground(new java.awt.Color(184, 233, 148));

        jLabel_livres1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_livres1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_livres1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_livres1.setText("Articles de recherches");

        javax.swing.GroupLayout jPanel_1_header1Layout = new javax.swing.GroupLayout(jPanel_1_header1);
        jPanel_1_header1.setLayout(jPanel_1_header1Layout);
        jPanel_1_header1Layout.setHorizontalGroup(
            jPanel_1_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1_header1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_livres1)
                .addGap(74, 74, 74))
        );
        jPanel_1_header1Layout.setVerticalGroup(
            jPanel_1_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_1_header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_livres1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        art_rech_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        art_rech_stat.setForeground(new java.awt.Color(242, 242, 242));
        art_rech_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        art_rech_stat.setText("jLabel9");

        javax.swing.GroupLayout jPanel_2Layout = new javax.swing.GroupLayout(jPanel_2);
        jPanel_2.setLayout(jPanel_2Layout);
        jPanel_2Layout.setHorizontalGroup(
            jPanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_1_header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(art_rech_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_2Layout.setVerticalGroup(
            jPanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_2Layout.createSequentialGroup()
                .addComponent(jPanel_1_header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(art_rech_stat)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel_3.setBackground(new java.awt.Color(130, 204, 221));

        jPanel_1_header2.setBackground(new java.awt.Color(130, 204, 221));

        jLabel_livres2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_livres2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_livres2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_livres2.setText("Revues");

        javax.swing.GroupLayout jPanel_1_header2Layout = new javax.swing.GroupLayout(jPanel_1_header2);
        jPanel_1_header2.setLayout(jPanel_1_header2Layout);
        jPanel_1_header2Layout.setHorizontalGroup(
            jPanel_1_header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1_header2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_livres2)
                .addGap(74, 74, 74))
        );
        jPanel_1_header2Layout.setVerticalGroup(
            jPanel_1_header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_1_header2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_livres2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        revue_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        revue_stat.setForeground(new java.awt.Color(255, 255, 255));
        revue_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        revue_stat.setText("jLabel8");

        javax.swing.GroupLayout jPanel_3Layout = new javax.swing.GroupLayout(jPanel_3);
        jPanel_3.setLayout(jPanel_3Layout);
        jPanel_3Layout.setHorizontalGroup(
            jPanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_1_header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(revue_stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_3Layout.setVerticalGroup(
            jPanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3Layout.createSequentialGroup()
                .addComponent(jPanel_1_header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(revue_stat)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jButton1.setText("graphe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(141, 141, 141))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_etudiantLayout = new javax.swing.GroupLayout(jPanel_etudiant);
        jPanel_etudiant.setLayout(jPanel_etudiantLayout);
        jPanel_etudiantLayout.setHorizontalGroup(
            jPanel_etudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_etudiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_etudiantLayout.setVerticalGroup(
            jPanel_etudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_etudiantLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_etudiantLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_etudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_etudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public  void AfficherInformation(String cin){
         try {
                
                //creation de la requete
                String query = "SELECT`etudiant`.`Nom`,`etudiant`.`Prenom`,`materiel`.`NomMat`,`materiel`.`typeMat`,`emprunt`.`date_emprunt`,`emprunt`.`date_retour`,`emprunt`.`duree`,`emprunt`.`retour`FROM `emprunt` , `etudiant`,`materiel` WHERE `emprunt`.`idMat`=`materiel`.`idMat` AND `etudiant`.`cin`=`emprunt`.`cin` AND `emprunt`.`cin`=?;";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,cin);
                rs=ps.executeQuery();
                Object[] row = new Object[jTableHistorique.getColumnCount()];
                while (rs.next()) {
                   row[0]=rs.getString("Nom");
                   row[1]=rs.getString("Prenom");
                   row[2]=rs.getString("NomMat");
                   row[3]=rs.getString("typeMat");
                   row[4]=rs.getString("date_emprunt");
                   row[5]=rs.getString("date_retour");
                   row[6]=rs.getString("duree");
                   row[7]=rs.getString("retour");
                   dfm.addRow(row);
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
               
            }
    }
    private void recherche_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_btnActionPerformed
        // TODO add your handling code here:
            // 
            String cin = cin_txt.getText();
            if(cin.equals("")){
                JOptionPane.showMessageDialog(this, "Champ cin est vide.");
            }else{
                //rechercher etudiant par cin
                if(Nouveau_emprunt.RechercherEtudiant(cin)){
                    //Affichege de l'étudiant
                    AfficherInformation(cin);
                    //Affichage de panel des informations pour l'étudiant
                    jPanel_etudiant.setVisible(true);
                    //Afficher statistiques:
                    int countlivre,countrevue,countart_rech,somme;
                    countlivre=AfficherStatistics("livre",cin);
                    countrevue=AfficherStatistics("revue",cin);
                    countart_rech=AfficherStatistics("article de recherche",cin);
                    somme=countlivre+countrevue+countart_rech;
                    //calculer pourcentage de chaque matériel:
                     prc_livre=countlivre*100/somme;
                     prc_revue=countrevue*100/somme;
                     prc_art_recherche=countart_rech*100/somme;
                     //affichage:
                    livre_stat.setText(String.valueOf(prc_livre)+"%");
                    revue_stat.setText(String.valueOf(prc_revue)+"%");
                    art_rech_stat.setText(String.valueOf(prc_art_recherche)+"%");


                }else{
                    JOptionPane.showMessageDialog(this, "Cet étudiant n'existe pas ");
                }
               
            }

    }//GEN-LAST:event_recherche_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(new Double(prc_revue), "Matériel", "revue");
        dataset.setValue(new Double(prc_art_recherche), "Matériel", "article de recherche");
        dataset.setValue(new Double(prc_livre), "Matériel", "livre");
        JFreeChart chart =ChartFactory.createBarChart("Statistiques des matériels des étudiants ", "Matériel", "valeus", dataset,PlotOrientation.VERTICAL,false,true,true);
        chart.setBackgroundPaint(Color.WHITE);
        chart.getTitle().setPaint(Color.black);
        chart.setBorderPaint(Color.black);
        
        CategoryPlot p =chart.getCategoryPlot();
      
        ChartFrame frame = new ChartFrame("Statistiques des matériels des étudiants",chart);
        frame.setVisible(true);
        frame.setSize(650,550);
    }//GEN-LAST:event_jButton1ActionPerformed

   public int AfficherStatistics(String typeMat,String cin){

        try {
                
                //creation de la requete
                String query = "SELECT count(`materiel`.`idMat`) as countMat FROM `materiel`,`emprunt`"
                + " WHERE  `materiel`.`idMat`=`emprunt`.`idMat` AND typeMat = ?  AND cin=?";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,typeMat);
                ps.setString(2,cin);
                rs=ps.executeQuery();
                if(rs.next()){
                   return rs.getInt("countMat");
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
               
            }
        return 0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel art_rech_stat;
    private javax.swing.JTextField cin_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_livres;
    private javax.swing.JLabel jLabel_livres1;
    private javax.swing.JLabel jLabel_livres2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_1;
    private javax.swing.JPanel jPanel_1_header;
    private javax.swing.JPanel jPanel_1_header1;
    private javax.swing.JPanel jPanel_1_header2;
    private javax.swing.JPanel jPanel_2;
    private javax.swing.JPanel jPanel_3;
    private javax.swing.JPanel jPanel_etudiant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHistorique;
    private javax.swing.JLabel livre_stat;
    private javax.swing.JButton recherche_btn;
    private javax.swing.JLabel revue_stat;
    // End of variables declaration//GEN-END:variables

}
