/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.BD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author AHMED
 */
public class Consulter_Utilisateur extends javax.swing.JInternalFrame {
    PreparedStatement ps;
   ResultSet rs;
   String query;
DefaultTableModel dfm =new DefaultTableModel();
    /**
     * Creates new form Consulter_Utilisateur
     */
    public Consulter_Utilisateur() {
        initComponents();
        
        jTable_utilisateur.setModel(dfm);
        dfm.addColumn("id");
        dfm.addColumn("nom");
        dfm.addColumn("prenom");
        dfm.addColumn("username");
        dfm.addColumn("mot de passe");
        dfm.addColumn("role");
        //
        jPanel1.setVisible(false);
        jPanel_modifié.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_rech = new javax.swing.JPanel();
        jLabel_rech = new javax.swing.JLabel();
        recherche_btn = new javax.swing.JButton();
        cin_txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_utilisateur = new javax.swing.JTable();
        supprimer_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_modifié = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        prenom_txt = new javax.swing.JTextField();
        username_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        responsable = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        Modifier_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel_rech.setBackground(new java.awt.Color(223, 230, 233));
        jPanel_rech.setForeground(new java.awt.Color(0, 102, 153));

        jLabel_rech.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_rech.setForeground(new java.awt.Color(0, 102, 153));
        jLabel_rech.setText("Entrez username de l'utilisateur :");

        recherche_btn.setBackground(new java.awt.Color(1, 50, 67));
        recherche_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        recherche_btn.setForeground(new java.awt.Color(255, 255, 255));
        recherche_btn.setText("Chercher");
        recherche_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherche_btnActionPerformed(evt);
            }
        });

        cin_txt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cin_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_rechLayout = new javax.swing.GroupLayout(jPanel_rech);
        jPanel_rech.setLayout(jPanel_rechLayout);
        jPanel_rechLayout.setHorizontalGroup(
            jPanel_rechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rechLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(cin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(recherche_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel_rechLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_rech, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_rechLayout.setVerticalGroup(
            jPanel_rechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_rechLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_rechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recherche_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTable_utilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom d'étudiant", "Nom de matériel", "Type de Matériel", "Date d'emprunt", "Date de retour", "Durée d'emprunt", "Status de retour"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_utilisateurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_utilisateur);

        supprimer_btn.setBackground(new java.awt.Color(1, 50, 67));
        supprimer_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supprimer_btn.setForeground(new java.awt.Color(255, 255, 255));
        supprimer_btn.setText("Supprimer");
        supprimer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Information de l'utilisateur :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(supprimer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(supprimer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prénom :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Username :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Passowrd:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Role :");

        nom_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        prenom_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        username_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txtActionPerformed(evt);
            }
        });

        id_txt.setEditable(false);
        id_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        password_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(responsable);
        responsable.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        responsable.setText("Responsable");

        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        admin.setText("Admin");

        Modifier_btn.setBackground(new java.awt.Color(1, 50, 67));
        Modifier_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Modifier_btn.setForeground(new java.awt.Color(255, 255, 255));
        Modifier_btn.setText("Modifier");
        Modifier_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_btnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("information modifié");

        javax.swing.GroupLayout jPanel_modifiéLayout = new javax.swing.GroupLayout(jPanel_modifié);
        jPanel_modifié.setLayout(jPanel_modifiéLayout);
        jPanel_modifiéLayout.setHorizontalGroup(
            jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_modifiéLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                                .addComponent(Modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                                .addComponent(responsable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(admin))
                            .addComponent(password_txt)))
                    .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prenom_txt)
                            .addComponent(nom_txt)
                            .addComponent(id_txt))))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_modifiéLayout.setVerticalGroup(
            jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(responsable)
                    .addComponent(admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modifier_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_modifié, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_rech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_modifié, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recherche_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherche_btnActionPerformed
        
        //
        String username = cin_txt.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(this, "Champ username est vide.");
        }else{
            //rechercher utilisateur par username
            if(RechercherUtilisateur(username)){
                //supprimer la ligne de la table
                for(int i=0;i<jTable_utilisateur.getRowCount();i++)
                       dfm.removeRow(i);
                //Affichege de l'utilisateur    
                AfficherInformation(username);
                
                //Affichage de panel des informations pour l'utilisateur
                jPanel1.setVisible(true);
                
                jPanel_modifié.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Cet utilisateur n'existe pas ");
            }

        }
    }//GEN-LAST:event_recherche_btnActionPerformed

    private void supprimer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer_btnActionPerformed
        
        int id, i=-1;
              i= jTable_utilisateur.getSelectedRow();
        TableModel tm=jTable_utilisateur.getModel();
        if(i!=-1)
        {
        id=(int) tm.getValueAt(i, 0);
            supprimer(id);
            dfm.removeRow(i);
        }
        else
          JOptionPane.showMessageDialog(this,"Aucune ligne n'a été sélectionée");   
        
    }//GEN-LAST:event_supprimer_btnActionPerformed

    private void Modifier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_btnActionPerformed
      
       int j=-1 ;j=jTable_utilisateur.getSelectedRow();
        TableModel tabm=jTable_utilisateur.getModel();
         if(j!=-1)
        
         {
           int  id=(int) tabm.getValueAt(j, 0); 
            int idU=Integer.parseInt(id_txt.getText());
    String nom=nom_txt.getText();
     String prnom=    prenom_txt.getText();
     String username=    username_txt.getText();
        
          //
     char[]password=password_txt.getPassword();
  String PassWord=new String(password);
                //
                String role;
                if(admin.isSelected())
                 role="Admin";
       
                else
                 role="Responsaple";
                
                if(! existe(username, id))
                 
                {modifiée(id,idU,nom, prnom,username,PassWord,role);
                    //
                   Object[] row = new Object[jTable_utilisateur.getColumnCount()];
                
                  dfm.removeRow(0);
                   row[0]=id;
                   row[1]=nom;
                   row[2]=prnom;
                   row[3]=username;
                   row[4]=PassWord;
                   row[5]=role;
                   
                   dfm.addRow(row);
                
               
                }
                else
               JOptionPane.showMessageDialog(this,"ce username est déja existe","erreur",JOptionPane.ERROR_MESSAGE); 
         }
        
          else
          JOptionPane.showMessageDialog(this,"Aucune ligne n'a été sélectionée");        
                
                
    }//GEN-LAST:event_Modifier_btnActionPerformed

    private void username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtActionPerformed

    private void cin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cin_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cin_txtActionPerformed

    private void jTable_utilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_utilisateurMouseClicked
        try{
            
             int i= jTable_utilisateur.getSelectedRow();
        TableModel tm=jTable_utilisateur.getModel();
       
        id_txt.setText(tm.getValueAt(i, 0).toString());
        nom_txt.setText(tm.getValueAt(i, 1).toString());
        prenom_txt.setText(tm.getValueAt(i, 2).toString());
        username_txt.setText(tm.getValueAt(i, 3).toString());
        password_txt.setText(tm.getValueAt(i, 4).toString());
        if(tm.getValueAt(i, 5).toString().equals("Admin"))
        { admin.setSelected(true);
        responsable.setSelected(false);}
        else
        {  responsable.setSelected(true);
           admin.setSelected(false);
        }
            
        }  catch(Exception e){
            JOptionPane.showMessageDialog(this,"clique sur la ligne valide\n"+e,"Tableau",JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_jTable_utilisateurMouseClicked

        public boolean RechercherUtilisateur(String username){
        try {
                //creation de la requete
                query = "SELECT id_utilisateur FROM `utilisateur` where username=?";
                
                 
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,username);
                rs=ps.executeQuery();
                return rs.next();
                     
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        return false;
        
        
        }
        public void  AfficherInformation(String username){
        
         try {
                //creation de la requete
              query = "SELECT * FROM `utilisateur` where username=?";
               
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,username);
                rs=ps.executeQuery();
                Object[] row = new Object[jTable_utilisateur.getColumnCount()];
                if(rs.next())
                 {   
                   row[0]=rs.getInt("id_utilisateur");
                   row[1]=rs.getString("nom");
                   row[2]=rs.getString("prenom");
                   row[3]=rs.getString("username");
                   row[4]=rs.getString("password");
                   row[5]=rs.getString("role");
                   
                   dfm.addRow(row);
                
                }
                     
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        public void supprimer(int id)
        {
        try {
                //creation de la requete
               query = "DELETE FROM `utilisateur` WHERE `utilisateur`.`id_utilisateur` = ?";
                
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setInt(1,id);
                int r=ps.executeUpdate();
                    if(r!=0){
                        JOptionPane.showMessageDialog(this,"c'utilisateur est supprimé avec succes"); 
                    }
                 
                     
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
        public void modifiée(int idpre ,int id,String nom ,String prenom ,String username ,String password ,String role){
        try {
                //creation de la requete
               query = "UPDATE `utilisateur` SET `id_utilisateur` = ?, `nom` = ?, `prenom` = ?, `username` = ?, `password` = ?, `role` = ? WHERE `utilisateur`.`id_utilisateur` = ?";
                
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setInt(1,id);
                ps.setString(2,nom);
                ps.setString(3,prenom);
                ps.setString(4,username);
                ps.setString(5,password);
                ps.setString(6,role);
                ps.setInt(7,idpre);
                
                int r=ps.executeUpdate();
                    if(r!=0){
                        JOptionPane.showMessageDialog(this,"c'utilisateur est modifié avec succes"); 
                    }
                 
                     
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            
        
        
        
        
        }}
        public static boolean existe( String username,int id ){
               String query = "select * from `utilisateur` where username=? and id_utilisateur <>?";
                PreparedStatement ps;
                ResultSet rs;
        try {
            //preparation de la requete
            ps=BD.connect().prepareStatement(query);
        
                //ajouter les valeurs de la requete
                ps.setString(1, username);
                 ps.setInt(2, id);
                
          rs =ps.executeQuery();
                return rs.next();
               } catch (SQLException ex) {
            Logger.getLogger(Nouveau_utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
               return false;
               }
        
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifier_btn;
    private javax.swing.JRadioButton admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cin_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_rech;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_modifié;
    private javax.swing.JPanel jPanel_rech;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_utilisateur;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JTextField prenom_txt;
    private javax.swing.JButton recherche_btn;
    private javax.swing.JRadioButton responsable;
    private javax.swing.JButton supprimer_btn;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
