/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.border.Border;

/**
 *
 * @author Mypc
 */
public final class home extends javax.swing.JFrame {
    /**
     * Creates new form home
     */
    public home() {
        super("Home");
        initComponents();
        AfficherImage();
        //ajouter un border à la  pannel de l'entete 
        Border borderpanel =BorderFactory.createMatteBorder(0,0,1,0,Color.white);
        panelHeader.setBorder(borderpanel);
        buttonHover();
        //centrer jframe
        this.setLocationRelativeTo(null);
       
        
    } 
    // fontion pour afficher image logo de l'entete
    public  void AfficherImage(){
        //recuperer l'image
        ImageIcon iconimg = new ImageIcon(getClass().getResource("/images/logo_home.png"));
        //adapter l'image a jlabel 
        Image img = iconimg.getImage().getScaledInstance(home_logo_jLabel.getWidth(),home_logo_jLabel.getHeight(),Image.SCALE_SMOOTH);
        //positionner l'image dans jlabel 
        home_logo_jLabel.setIcon(new ImageIcon(img));
        
    }
    //creation d'une fonction pour ajouter hover à les bouttons de menu
    public void buttonHover(){
        //recuperer tous les composants dans jpanel menu
        Component[] comps = panelMenu.getComponents();
        for(Component comp : comps){
            if(comp instanceof JButton){
                JButton button =(JButton) comp;
                // ajouter l'action au jbutton
                button.addMouseListener(new MouseAdapter(){
                    @Override
                    public void mouseEntered(MouseEvent evt){
                        button.setForeground(Color.orange);
                    }
                });
                 button.addMouseListener(new MouseAdapter(){
                    @Override
                    public void mouseExited(MouseEvent evt){
                        button.setForeground(Color.white);
                    }//mouseExited
                });
                
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        home_logo_jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        statistics_etudiant_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nv_emprunt_btn = new javax.swing.JButton();
        etudiants_SansRespect_delais_btn = new javax.swing.JButton();
        consulter_etudiant_btn = new javax.swing.JButton();
        retour_pret_btn = new javax.swing.JButton();
        jLabel_prets = new javax.swing.JLabel();
        pret_retard_btn2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelMenu.setBackground(new java.awt.Color(0, 51, 102));

        panelHeader.setBackground(new java.awt.Color(0, 51, 90));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("MENU");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(home_logo_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_logo_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 163, 188));
        jLabel2.setText("Emprunt");

        statistics_etudiant_btn.setBackground(new java.awt.Color(0, 51, 102));
        statistics_etudiant_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statistics_etudiant_btn.setForeground(new java.awt.Color(255, 255, 255));
        statistics_etudiant_btn.setText("                            Statistiques des matériels des étudiants");
        statistics_etudiant_btn.setBorder(null);
        statistics_etudiant_btn.setContentAreaFilled(false);
        statistics_etudiant_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistics_etudiant_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(96, 163, 188));
        jLabel3.setText("Etudiants");

        nv_emprunt_btn.setBackground(new java.awt.Color(0, 51, 102));
        nv_emprunt_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nv_emprunt_btn.setForeground(new java.awt.Color(255, 255, 255));
        nv_emprunt_btn.setText("  Nouveau emprunt");
        nv_emprunt_btn.setBorder(null);
        nv_emprunt_btn.setContentAreaFilled(false);
        nv_emprunt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nv_emprunt_btnActionPerformed(evt);
            }
        });

        etudiants_SansRespect_delais_btn.setBackground(new java.awt.Color(0, 51, 102));
        etudiants_SansRespect_delais_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etudiants_SansRespect_delais_btn.setForeground(new java.awt.Color(255, 255, 255));
        etudiants_SansRespect_delais_btn.setText("Etudiants ne respectent pas les délais");
        etudiants_SansRespect_delais_btn.setBorder(null);
        etudiants_SansRespect_delais_btn.setContentAreaFilled(false);
        etudiants_SansRespect_delais_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiants_SansRespect_delais_btnActionPerformed(evt);
            }
        });

        consulter_etudiant_btn.setBackground(new java.awt.Color(0, 51, 102));
        consulter_etudiant_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        consulter_etudiant_btn.setForeground(new java.awt.Color(255, 255, 255));
        consulter_etudiant_btn.setText("        Consulter un étudiant");
        consulter_etudiant_btn.setBorder(null);
        consulter_etudiant_btn.setContentAreaFilled(false);
        consulter_etudiant_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulter_etudiant_btnActionPerformed(evt);
            }
        });

        retour_pret_btn.setBackground(new java.awt.Color(0, 51, 102));
        retour_pret_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retour_pret_btn.setForeground(new java.awt.Color(255, 255, 255));
        retour_pret_btn.setText("Retourner un prêt");
        retour_pret_btn.setBorder(null);
        retour_pret_btn.setContentAreaFilled(false);
        retour_pret_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour_pret_btnActionPerformed(evt);
            }
        });

        jLabel_prets.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_prets.setForeground(new java.awt.Color(96, 163, 188));
        jLabel_prets.setText("Retour des prêts");

        pret_retard_btn2.setBackground(new java.awt.Color(0, 51, 102));
        pret_retard_btn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pret_retard_btn2.setForeground(new java.awt.Color(255, 255, 255));
        pret_retard_btn2.setText(" Prêts sensibles au retard");
        pret_retard_btn2.setBorder(null);
        pret_retard_btn2.setContentAreaFilled(false);
        pret_retard_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pret_retard_btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel_prets, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statistics_etudiant_btn))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etudiants_SansRespect_delais_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nv_emprunt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pret_retard_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulter_etudiant_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retour_pret_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(nv_emprunt_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(consulter_etudiant_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statistics_etudiant_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etudiants_SansRespect_delais_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pret_retard_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_prets, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(retour_pret_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statistics_etudiant_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistics_etudiant_btnActionPerformed
        // TODO add your handling code here:
         Statistics_materiels statistics_materiels_form=new Statistics_materiels();
        //Appeler la methode AfficherForm
        AfficherForm(statistics_materiels_form);
        
    }//GEN-LAST:event_statistics_etudiant_btnActionPerformed

    private void nv_emprunt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nv_emprunt_btnActionPerformed
         //creer une instance de jinternalFFrame  Nouveau_emprunt
        Nouveau_emprunt nvEmpruntForm=new Nouveau_emprunt();
        //Appeler la methode AfficherForm
        AfficherForm(nvEmpruntForm);
    }//GEN-LAST:event_nv_emprunt_btnActionPerformed

    private void etudiants_SansRespect_delais_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiants_SansRespect_delais_btnActionPerformed
        // TODO add your handling code here:
         //creer une instance de jinternalFFrame  Nouveau_emprunt
        Etudiants_sans_respect_delais frame_etud_sans_respect_dalais=new Etudiants_sans_respect_delais();
        //Appeler la methode AfficherForm
        AfficherForm(frame_etud_sans_respect_dalais);
    }//GEN-LAST:event_etudiants_SansRespect_delais_btnActionPerformed

    private void consulter_etudiant_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulter_etudiant_btnActionPerformed
        // TODO add your handling code here:
         //creer une instance de jinternalFFrame  Nouveau_emprunt
        Consulter_Etudiant frame_consulter_etudiant=new Consulter_Etudiant();
        //Appeler la methode AfficherForm
        AfficherForm(frame_consulter_etudiant);
        
    }//GEN-LAST:event_consulter_etudiant_btnActionPerformed

    private void retour_pret_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour_pret_btnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_retour_pret_btnActionPerformed

    private void pret_retard_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pret_retard_btn2ActionPerformed
        // TODO add your handling code here:
           //creer une instance de jinternalFFrame  Nouveau_emprunt
        Prets_retard frame_prets_retard=new Prets_retard();
        //Appeler la methode AfficherForm
        AfficherForm(frame_prets_retard);
        
    }//GEN-LAST:event_pret_retard_btn2ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    //Creation de la methode afficherForm pour afficher JInternalframe dans jDesktopPane1
    public void AfficherForm(JInternalFrame frame){
        jDesktopPane1.removeAll();
        /////
        //  titlebar invisible
           setRootPaneCheckingEnabled(false);
           javax.swing.plaf.InternalFrameUI ifu= frame.getUI();
           ((javax.swing.plaf.basic.BasicInternalFrameUI)ifu).setNorthPane(null);
        ////
        //ajouter le meme size de jdesktoppane 
        frame.setSize(jDesktopPane1.getSize());
        //supprimer le border
        frame.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jDesktopPane1.add(frame).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulter_etudiant_btn;
    private javax.swing.JButton etudiants_SansRespect_delais_btn;
    private javax.swing.JLabel home_logo_jLabel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_prets;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nv_emprunt_btn;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton pret_retard_btn2;
    private javax.swing.JButton retour_pret_btn;
    private javax.swing.JButton statistics_etudiant_btn;
    // End of variables declaration//GEN-END:variables
}
