/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.BD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author AHMED
 */
public class Nouveau_utilisateur extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nouveau_utilisateur
     */
    public Nouveau_utilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_modifié = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        prenom_txt = new javax.swing.JTextField();
        username_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        responsable = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        ajouter_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prénom :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Username :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Passowrd:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Role :");

        nom_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        prenom_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prenom_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenom_txtActionPerformed(evt);
            }
        });

        username_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_txtActionPerformed(evt);
            }
        });

        password_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(responsable);
        responsable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        responsable.setText("Responsable");
        responsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsableActionPerformed(evt);
            }
        });

        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        ajouter_btn.setBackground(new java.awt.Color(1, 50, 67));
        ajouter_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ajouter_btn.setForeground(new java.awt.Color(255, 255, 255));
        ajouter_btn.setText("Ajouter");
        ajouter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouter_btnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("information de l'utilisateur :");

        javax.swing.GroupLayout jPanel_modifiéLayout = new javax.swing.GroupLayout(jPanel_modifié);
        jPanel_modifié.setLayout(jPanel_modifiéLayout);
        jPanel_modifiéLayout.setHorizontalGroup(
            jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                                        .addComponent(responsable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(admin))
                                    .addComponent(prenom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(ajouter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel_modifiéLayout.setVerticalGroup(
            jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_modifiéLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(73, 73, 73)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(prenom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel_modifiéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin)
                    .addComponent(responsable)
                    .addComponent(jLabel7))
                .addGap(90, 90, 90)
                .addComponent(ajouter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_modifié, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_modifié, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_txtActionPerformed

    private void ajouter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouter_btnActionPerformed

    String nom        =nom_txt.getText();
    String prenom     =prenom_txt.getText();
    String username  =username_txt.getText();
       
          //
    char[]password=password_txt.getPassword();
    String PassWord=new String(password);
                //
    String role;
                if(admin.isSelected())
                 role="admin";
       
                else
                 role="responsaple";
                
               if(nom.equals("") || prenom .equals("") || username.equals("") || PassWord.equals(""))
               {   
               JOptionPane.showMessageDialog(this,"il faut remplir tous les champs");  
         }
        
             else
               { 
               ajouter(nom,prenom,username,PassWord,role);
    }                                            
 
                                          

   
            
        
       
       

    }//GEN-LAST:event_ajouter_btnActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void responsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsableActionPerformed

    private void prenom_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenom_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenom_txtActionPerformed

               public void ajouter(String nom,String prenom,String username,String PassWord,String role){
               if(!existe( username )){
                 try {
                //creation de la requete
                String query = "INSERT INTO `utilisateur` ( `nom`, `prenom`, `username`, `password`, `role`) VALUES (?,?,?,?,?)";
                PreparedStatement ps;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1, nom);
                ps.setString(2, prenom);
                ps.setString(3, username);
                ps.setString(4, PassWord);
                ps.setString(5, role);
                int  r=ps.executeUpdate();
                if(r!=0){
                    JOptionPane.showMessageDialog(this,"le nouveau utilisateur est enregistré avec succes"); 
             
                }else{
                    //
                    JOptionPane.showMessageDialog(this,"erreur dans l'ajout","erreur",JOptionPane.ERROR_MESSAGE); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
               }
               
               else
               JOptionPane.showMessageDialog(this,"ce username est déja existe","erreur",JOptionPane.ERROR_MESSAGE); 
               }
    
               
               
       public static boolean existe( String username ){
               String query = "select * from `utilisateur` where username=?";
                PreparedStatement ps;
                ResultSet rs;
        try {
            //preparation de la requete
            ps=BD.connect().prepareStatement(query);
        
                //ajouter les valeurs de la requete
                ps.setString(1, username);
          rs =ps.executeQuery();
                return rs.next();
               } catch (SQLException ex) {
            Logger.getLogger(Nouveau_utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
               return false;
               }
               
               
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.JButton ajouter_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_modifié;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JTextField prenom_txt;
    private javax.swing.JRadioButton responsable;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
