/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package forms;

import classes.BD;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mypc
 */
public class Nouveau_emprunt extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nouveau_emprunt
     */
    public Nouveau_emprunt() {
        initComponents();
        //panel des informations des étudiant invisible par défaut:
        Panel_nvEtudiant.setVisible(false);
        liste_Mat_2_panel.setVisible(false);
        //remplir_combo1
        try {
                //creation de la requete
                String query = "SELECT distinct typeMat FROM `materiel`";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                rs=ps.executeQuery();
                jComboBox_Mat_1.removeAllItems();
                
                while(rs.next()){
                    jComboBox_Mat_1.addItem(rs.getString("typeMat"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
    
      


    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jComboBox_Mat_1 = new javax.swing.JComboBox<>();
        jButton_Mat_1 = new javax.swing.JButton();
        liste_Mat_2_panel = new javax.swing.JPanel();
        jComboBox_mat_2 = new javax.swing.JComboBox<>();
        jButton_Mat_2 = new javax.swing.JButton();
        jLabel_type_Mat_2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Panel_nvEtudiant = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cin_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        err_cin_lbl = new javax.swing.JLabel();
        err_nom_lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prenom_txt = new javax.swing.JTextField();
        err_prenom_lbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mail_txt = new javax.swing.JTextField();
        err_mail_lbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phone_txt = new javax.swing.JTextField();
        err_phone_lbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        duree_txt = new javax.swing.JTextField();
        err_duree_lbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Enregistrer un nouveau emprunt");

        jPanel1.setBackground(new java.awt.Color(96, 163, 188));

        jComboBox_Mat_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Mat_1.setText("Rechercher");
        jButton_Mat_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Mat_1ActionPerformed(evt);
            }
        });

        liste_Mat_2_panel.setBackground(new java.awt.Color(96, 163, 188));

        jComboBox_mat_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_Mat_2.setText("Rechercher");
        jButton_Mat_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Mat_2ActionPerformed(evt);
            }
        });

        jLabel_type_Mat_2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_type_Mat_2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel_type_Mat_2.setText("  Liste des livres :");

        javax.swing.GroupLayout liste_Mat_2_panelLayout = new javax.swing.GroupLayout(liste_Mat_2_panel);
        liste_Mat_2_panel.setLayout(liste_Mat_2_panelLayout);
        liste_Mat_2_panelLayout.setHorizontalGroup(
            liste_Mat_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, liste_Mat_2_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(liste_Mat_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_type_Mat_2)
                    .addGroup(liste_Mat_2_panelLayout.createSequentialGroup()
                        .addComponent(jComboBox_mat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton_Mat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        liste_Mat_2_panelLayout.setVerticalGroup(
            liste_Mat_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liste_Mat_2_panelLayout.createSequentialGroup()
                .addComponent(jLabel_type_Mat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(liste_Mat_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_mat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Mat_2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Choisir le type du matériel :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_Mat_1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton_Mat_1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(liste_Mat_2_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Mat_1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Mat_1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(liste_Mat_2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Informations des étudiants:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("CIN:");

        cin_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nom:");

        nom_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        err_cin_lbl.setForeground(new java.awt.Color(255, 51, 51));

        err_nom_lbl.setForeground(new java.awt.Color(255, 51, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Prénom:");

        prenom_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prenom_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenom_txtActionPerformed(evt);
            }
        });

        err_prenom_lbl.setForeground(new java.awt.Color(255, 51, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email:");

        mail_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        err_mail_lbl.setForeground(new java.awt.Color(255, 51, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Numéro de téléphone:");

        phone_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        err_phone_lbl.setForeground(new java.awt.Color(255, 51, 51));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 153, 0));
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Vider les champs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Durée d'emprunt:");

        duree_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        err_duree_lbl.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout Panel_nvEtudiantLayout = new javax.swing.GroupLayout(Panel_nvEtudiant);
        Panel_nvEtudiant.setLayout(Panel_nvEtudiantLayout);
        Panel_nvEtudiantLayout.setHorizontalGroup(
            Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                        .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(err_prenom_lbl)
                                    .addComponent(err_nom_lbl)
                                    .addComponent(err_cin_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nom_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(prenom_txt)
                                    .addComponent(cin_txt))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_nvEtudiantLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err_mail_lbl)
                                    .addComponent(err_phone_lbl)
                                    .addComponent(mail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duree_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(err_duree_lbl)))
                            .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        Panel_nvEtudiantLayout.setVerticalGroup(
            Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(err_cin_lbl))
                    .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(err_phone_lbl)))
                .addGap(18, 18, 18)
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(err_nom_lbl)
                    .addComponent(err_mail_lbl))
                .addGap(26, 26, 26)
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(prenom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(duree_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(err_prenom_lbl)
                .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(Panel_nvEtudiantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(102, Short.MAX_VALUE))
                    .addGroup(Panel_nvEtudiantLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(err_duree_lbl)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_nvEtudiant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_nvEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenom_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenom_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenom_txtActionPerformed

    private void jButton_Mat_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Mat_1ActionPerformed
        // TODO add your handling code here:
        Panel_nvEtudiant.setVisible(false);

        //recuperer le type de combobox1:
        String type=jComboBox_Mat_1.getSelectedItem().toString();
        jLabel_type_Mat_2.setText("Liste des "+type+"s : ");
         try {
                //creation de la requete
                String query = "SELECT nomMat FROM `materiel` where typeMat='"+type+"'";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                rs=ps.executeQuery();
                jComboBox_mat_2.removeAllItems();
                
                while(rs.next()){
                    jComboBox_mat_2.addItem(rs.getString("nomMat"));
                }
                liste_Mat_2_panel.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
    }//GEN-LAST:event_jButton_Mat_1ActionPerformed
    public static int idMat;
    public static int qte;
    private void jButton_Mat_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Mat_2ActionPerformed
        // TODO add your handling code here:
        try {
                //creation de la requete
                String query = "SELECT Qte,idMat FROM `materiel` where nomMat=?";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,jComboBox_mat_2.getSelectedItem().toString() );
                rs=ps.executeQuery();
                if(rs.next()){
                    qte=rs.getInt("Qte");
                    idMat=rs.getInt("idMat");
                }
                if(qte > 0)
                {
                    //display the panel : information etudiants
                    Panel_nvEtudiant.setVisible(true);
                }else{
                     JOptionPane.showMessageDialog(this, "Ce matériel n'est pas disponible pour le moment."
                     ,"Info",JOptionPane.WARNING_MESSAGE);
                        
                }
                     
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jButton_Mat_2ActionPerformed
    //verifier if isnumeric:
    public static boolean isInteger(String strNum) {
    if (strNum == null) {
        return false;
    }
    try {
        double d = Integer.parseInt(strNum);
    } catch (NumberFormatException nfe) {
        return false;
    }
    return true;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           //Enregistrer un vouveau compte etudiant
           String cin=cin_txt.getText();
           String nom=nom_txt.getText();
           String prenom=prenom_txt.getText();
           String mail=mail_txt.getText();
           String phone=phone_txt.getText();
           String duree=duree_txt.getText();
           //alerts si les champs sont vides.
           if(cin_txt.getText().equals("")){
               err_cin_lbl.setText("* champ CIN est vide .");
           }else if(nom_txt.getText().equals("")){
                err_nom_lbl.setText("* champ Nom est vide .");
           }else if(prenom_txt.getText().equals("")){
                err_prenom_lbl.setText("* champ Prénom est vide .");
           }else if(mail_txt.getText().equals("")){
                err_mail_lbl.setText("* champ Email est vide .");
           }else if(phone_txt.getText().equals("")){
                err_phone_lbl.setText("* champ Numéro de téléphone  est vide .");
           }else if(duree_txt.getText().equals("")){
                err_duree_lbl.setText("* champ Durée  est vide .");
           }else if(isInteger(duree)==false){
                err_duree_lbl.setText("* champ Durée  doit etre entier .");
           }else { 
               //rechercher etudiant:
               if(RechercherEtudiant(cin)){
                   try {
                       //verifier if l'etudiant pas encore retourner le materiel
                       if(!IsEmprunteSansRetour(cin)){
                           //emprunter
                           Emprunter(cin,idMat,duree);            
                       }
                       else{
                           JOptionPane.showMessageDialog(this, "Cet étudiant n'a pas encore rendu ce matériel");
                       }
                   } catch (SQLException ex) {
                       Logger.getLogger(Nouveau_emprunt.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }else{
                   //Message acceptaion
                    int a=JOptionPane.showConfirmDialog(this,"Cet étudiant n'a pas encore de compte ."
                            + "Voulez-vous enregister un compte pour cet étudiant?"); 
                    if(a==JOptionPane.YES_OPTION){  
                            EnregisterEtudiant(cin,nom,prenom,mail,phone,duree);
                    }else if (a==JOptionPane.NO_OPTION){
                        JOptionPane.showMessageDialog(this, "L'emprunt est annulé.");
                    }  
               }
               
           }
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    //rechercher etudiant:
    public static boolean RechercherEtudiant(String cin){
         try {
                //creation de la requete
                String query = "SELECT cin FROM `etudiant` where cin=?";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,cin);
                rs=ps.executeQuery();
                return rs.next();
                     
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        return false;
         
    }
    public static void  Emprunter(String cin,int idMat,String duree) throws SQLException{
         // enregistrer un nouveau emprunt pour cet étudiant:
                   String query = "INSERT INTO `emprunt` (`cin`,`idMat`,`date_emprunt`,`duree`,`retour`) values(?,?,?,?,?)";
                    PreparedStatement ps;
                    //preparation de la requete
                    ps=BD.connect().prepareStatement(query);
                    //
                    //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    LocalDateTime now = LocalDateTime.now();//date emprunt
                    //Date retour:
                    //ajouter les valeurs d la requete
                    ps.setString(1, cin);
                    ps.setInt(2, idMat);
                    ps.setString(3, now.toString());
                    ps.setInt(4,Integer.parseInt(duree));
                    ps.setInt(5, 0);

                    int r=ps.executeUpdate();
                    if(r!=0){
                        UpdateQte();
                        JOptionPane.showMessageDialog(new Nouveau_emprunt(),"le nouveau emprunt est enregistré avec succes"); 
                    }
    }
    public static void EnregisterEtudiant(String cin,String nom,String prenom,String mail,String phone,String duree){
        try {
                //creation de la requete
                String query = "INSERT INTO `etudiant` values (?,?,?,?,?)";
                PreparedStatement ps;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1, cin);
                ps.setString(2, nom);
                ps.setString(3, prenom);
                ps.setString(4, mail);
                ps.setString(5, phone);
                int  r=ps.executeUpdate();
                if(r!=0){
                    JOptionPane.showMessageDialog(new Nouveau_emprunt(),"le nouveau étudiant est enregistré avec succes"); 
                    ////////////Enregister emprunt pour cet etudiant
                    Emprunter(cin,idMat,duree); 

                }else{
                    //
                    JOptionPane.showMessageDialog(new Nouveau_emprunt(),"erreur dans l'ajout","erreur",JOptionPane.ERROR_MESSAGE); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    public static boolean IsEmprunteSansRetour(String cin){
         try {
                //creation de la requete
                String query = "SELECT retour FROM `emprunt` WHERE cin=? AND idMat=?";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1, cin);
                ps.setInt(2, idMat);
                rs=ps.executeQuery();
                if(rs.next()){                   
                    ////////////Enregister emprunt pour cet etudiant
                    int retour =rs.getInt("retour");
                    if(retour==0){
                        return true;
                    }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
         return false;
    }
    public static void UpdateQte(){
        try {
            String query = "UPDATE `materiel`  SET Qte=? WHERE idMat=?";
            PreparedStatement ps;
            //preparation de la requete
            ps=BD.connect().prepareStatement(query);
            //ajouter les valeurs d la requete
            qte-=1;
            ps.setInt(1, qte);
            ps.setInt(2, idMat);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Nouveau_emprunt.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_nvEtudiant;
    private javax.swing.JTextField cin_txt;
    private javax.swing.JTextField duree_txt;
    private javax.swing.JLabel err_cin_lbl;
    private javax.swing.JLabel err_duree_lbl;
    private javax.swing.JLabel err_mail_lbl;
    private javax.swing.JLabel err_nom_lbl;
    private javax.swing.JLabel err_phone_lbl;
    private javax.swing.JLabel err_prenom_lbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Mat_1;
    private javax.swing.JButton jButton_Mat_2;
    private javax.swing.JComboBox<String> jComboBox_Mat_1;
    private javax.swing.JComboBox<String> jComboBox_mat_2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_type_Mat_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel liste_Mat_2_panel;
    private javax.swing.JTextField mail_txt;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JTextField prenom_txt;
    // End of variables declaration//GEN-END:variables
}
