/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package forms;

import classes.BD;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Mypc
 */

public class Statistics_materiels extends javax.swing.JInternalFrame {
     
    int prc_livre,prc_revue,prc_art_recherche;
    /**
     * Creates new form Statistics_materiels
     */
    public Statistics_materiels() {
        initComponents();
        //ajouter un border à la  pannel de l'entete 
        Border border_header_1 =BorderFactory.createMatteBorder(0,0,3,0,new Color(255, 159, 26));
        jPanel_1_header.setBorder(border_header_1);
        Border border_header_2 =BorderFactory.createMatteBorder(0,0,3,0,new Color(52, 172, 224));
        jPanel_2_header.setBorder(border_header_2);
        Border border_header_3 =BorderFactory.createMatteBorder(0,0,3,0,new Color(38, 222, 129));
        jPanel_3_header.setBorder(border_header_3);
        //Afficher statistiques:
        int countlivre,countrevue,countart_rech,somme;
        countlivre=AfficherStatistics("livre");
        countrevue=AfficherStatistics("revue");
        countart_rech=AfficherStatistics("article de recherche");
        somme=countlivre+countrevue+countart_rech;
                    //calculer pourcentage de chaque matériel:
                     prc_livre=countlivre*100/somme;
                     prc_revue=countrevue*100/somme;
                     prc_art_recherche=countart_rech*100/somme;
                     //affichage:
                    livre_stat.setText(String.valueOf(prc_livre)+"%");
                    revue_stat.setText(String.valueOf(prc_revue)+"%");
                    art_rech_stat.setText(String.valueOf(prc_art_recherche)+"%");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_2 = new javax.swing.JPanel();
        jPanel_2_header = new javax.swing.JPanel();
        jLabel_revues = new javax.swing.JLabel();
        revue_stat = new javax.swing.JLabel();
        jPanel_1 = new javax.swing.JPanel();
        jPanel_1_header = new javax.swing.JPanel();
        jLabel_livres = new javax.swing.JLabel();
        livre_stat = new javax.swing.JLabel();
        jPanel_3 = new javax.swing.JPanel();
        jPanel_3_header = new javax.swing.JPanel();
        jLabel_revues1 = new javax.swing.JLabel();
        art_rech_stat = new javax.swing.JLabel();
        graphe = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel_2.setBackground(new java.awt.Color(130, 204, 221));

        jPanel_2_header.setBackground(new java.awt.Color(130, 204, 221));

        jLabel_revues.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_revues.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_revues.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_revues.setText("Revues");

        javax.swing.GroupLayout jPanel_2_headerLayout = new javax.swing.GroupLayout(jPanel_2_header);
        jPanel_2_header.setLayout(jPanel_2_headerLayout);
        jPanel_2_headerLayout.setHorizontalGroup(
            jPanel_2_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_2_headerLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jLabel_revues)
                .addGap(86, 86, 86))
        );
        jPanel_2_headerLayout.setVerticalGroup(
            jPanel_2_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_2_headerLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel_revues)
                .addGap(23, 23, 23))
        );

        revue_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        revue_stat.setForeground(new java.awt.Color(255, 255, 255));
        revue_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_2Layout = new javax.swing.GroupLayout(jPanel_2);
        jPanel_2.setLayout(jPanel_2Layout);
        jPanel_2Layout.setHorizontalGroup(
            jPanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_2_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(revue_stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_2Layout.setVerticalGroup(
            jPanel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_2Layout.createSequentialGroup()
                .addComponent(jPanel_2_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(revue_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel_1.setBackground(new java.awt.Color(255, 177, 66));

        jPanel_1_header.setBackground(new java.awt.Color(255, 177, 66));

        jLabel_livres.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_livres.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_livres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_livres.setText("Livres");

        javax.swing.GroupLayout jPanel_1_headerLayout = new javax.swing.GroupLayout(jPanel_1_header);
        jPanel_1_header.setLayout(jPanel_1_headerLayout);
        jPanel_1_headerLayout.setHorizontalGroup(
            jPanel_1_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1_headerLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel_livres)
                .addGap(96, 96, 96))
        );
        jPanel_1_headerLayout.setVerticalGroup(
            jPanel_1_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1_headerLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel_livres)
                .addGap(23, 23, 23))
        );

        livre_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        livre_stat.setForeground(new java.awt.Color(255, 255, 255));
        livre_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_1Layout = new javax.swing.GroupLayout(jPanel_1);
        jPanel_1.setLayout(jPanel_1Layout);
        jPanel_1Layout.setHorizontalGroup(
            jPanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_1_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livre_stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_1Layout.setVerticalGroup(
            jPanel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_1Layout.createSequentialGroup()
                .addComponent(jPanel_1_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(livre_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_3.setBackground(new java.awt.Color(184, 233, 148));

        jPanel_3_header.setBackground(new java.awt.Color(184, 233, 148));

        jLabel_revues1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_revues1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel_revues1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_revues1.setText("Articles de recherche");

        javax.swing.GroupLayout jPanel_3_headerLayout = new javax.swing.GroupLayout(jPanel_3_header);
        jPanel_3_header.setLayout(jPanel_3_headerLayout);
        jPanel_3_headerLayout.setHorizontalGroup(
            jPanel_3_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3_headerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel_revues1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel_3_headerLayout.setVerticalGroup(
            jPanel_3_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3_headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_revues1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        art_rech_stat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        art_rech_stat.setForeground(new java.awt.Color(255, 255, 255));
        art_rech_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel_3Layout = new javax.swing.GroupLayout(jPanel_3);
        jPanel_3.setLayout(jPanel_3Layout);
        jPanel_3Layout.setHorizontalGroup(
            jPanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_3_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(art_rech_stat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_3Layout.setVerticalGroup(
            jPanel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_3Layout.createSequentialGroup()
                .addComponent(jPanel_3_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(art_rech_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        graphe.setText("graphe");
        graphe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grapheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graphe)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100)
                .addComponent(graphe)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grapheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grapheActionPerformed
     
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(new Double(prc_revue), "Matériel", "revue");
        dataset.setValue(new Double(prc_art_recherche), "Matériel", "article de recherche");
        dataset.setValue(new Double(prc_livre), "Matériel", "livre");
        JFreeChart chart =ChartFactory.createBarChart("Statistiques des matériels des étudiants ", "Matériel", "valeus", dataset,PlotOrientation.VERTICAL,false,true,true);
        chart.setBackgroundPaint(Color.WHITE);
        chart.getTitle().setPaint(Color.black);
        chart.setBorderPaint(Color.black);
        
        CategoryPlot p =chart.getCategoryPlot();
      
        ChartFrame frame = new ChartFrame("Statistiques des matériels des étudiants",chart);
        frame.setVisible(true);
        frame.setSize(650,550);
   
    }//GEN-LAST:event_grapheActionPerformed

public int AfficherStatistics(String typeMat){

        try {
                
                //creation de la requete
                String query = "SELECT count(`materiel`.`idMat`) as countMat FROM `materiel`,`emprunt` "
                        + "WHERE  `materiel`.`idMat`=`emprunt`.`idMat`  AND typeMat = ? ";
                PreparedStatement ps;
                ResultSet rs;
                //preparation de la requete
                ps=BD.connect().prepareStatement(query);
                //ajouter les valeurs de la requete
                ps.setString(1,typeMat);
                rs=ps.executeQuery();
                if(rs.next()){
                   return rs.getInt("countMat");
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
               
            }
        return 0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel art_rech_stat;
    private javax.swing.JButton graphe;
    private javax.swing.JLabel jLabel_livres;
    private javax.swing.JLabel jLabel_revues;
    private javax.swing.JLabel jLabel_revues1;
    private javax.swing.JPanel jPanel_1;
    private javax.swing.JPanel jPanel_1_header;
    private javax.swing.JPanel jPanel_2;
    private javax.swing.JPanel jPanel_2_header;
    private javax.swing.JPanel jPanel_3;
    private javax.swing.JPanel jPanel_3_header;
    private javax.swing.JLabel livre_stat;
    private javax.swing.JLabel revue_stat;
    // End of variables declaration//GEN-END:variables
}
